// Generated by CoffeeScript 1.4.0
(function() {
  var exec, nhacso;

  exec = require('child_process').exec;

  nhacso = require('./cNhacso');

  task('nhacso:song', 'fetching from nhacso', function() {
    return nhacso.fetchAlbums(500000, 500100);
  });

}).call(this);
